
services:
  backend:
    build: .
    container_name: peeltalk-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/peeltalk
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: peeltalk-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: peeltalk-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data:
